env:
  # APP OPENCTI
  APP__ADMIN__EMAIL: admin@admin.io
  APP__ADMIN__PASSWORD: changeme
  APP__ADMIN__TOKEN: <insert random UUID here>
  APP__BASE_PATH: "/"
  APP__GRAPHQL__PLAYGROUND__ENABLED: false
  APP__GRAPHQL__PLAYGROUND__FORCE_DISABLED_INTROSPECTION: false
  NODE_OPTIONS: "--max-old-space-size=8096"
  PROVIDERS__LOCAL__STRATEGY: LocalStrategy
  # MINIO
  MINIO__ENDPOINT: opencti-minio
  MINIO__PORT: 9000
  MINIO__ACCESS_KEY: user
  MINIO__SECRET_KEY: changeme
  MINIO__USE_SSL: false
  # ELASTICSEARCH
  ELASTICSEARCH__URL: http://opencti-elasticsearch:9200
  # RABBITMQ
  RABBITMQ__HOSTNAME: opencti-rabbitmq
  RABBITMQ__PORT_MANAGEMENT: 15672
  RABBITMQ__PORT: 5672
  RABBITMQ__USERNAME: user
  RABBITMQ__PASSWORD: changeme
  # REDIS
  REDIS__HOSTNAME: opencti-redis-master
  REDIS__PORT: 6379
  REDIS__MODE: single
  # METRICS AND HEALTHCHECK
  APP__TELEMETRY__METRICS__ENABLED: true
  APP__HEALTH_ACCESS_KEY: changeme

elasticsearch:
  enabled: true

  extraEnvVars:
    - name: ES_JAVA_OPTS
      # Important to tune for larger deployments
      value: "-Xms1g -Xmx1g"

  sysctlImage:
    enabled: false

  # You can choose to have a separate master and data ES node, per the defaults
  master:
    masterOnly: false
    replicaCount: 1
    persistence:
      enabled: true
      # Define the Persistent Volume Chain size for storing ES data default for other components (redis, minio etc.) is 8Gi
      size: "100Gi"
    # If you don't specify this, Kubernetes will automatically set them for you
    resources:
      requests:
        memory: "2Gi"
      limits:
        memory: "2Gi"
  data:
    # To have only one combined ES master + data node
    replicaCount: 0
  ingest:
    replicaCount: 0
  coordinating:
    replicaCount: 0
      

minio:
  enabled: true
  mode: standalone
  auth:
    rootUser: user
    rootPassword: changeme

  persistence:
    enabled: true


rabbitmq:
  enabled: true
  replicaCount: 1
  clustering:
    enabled: false

  auth:
    username: user
    password: changeme
    erlangCookie: changeme

  persistence:
    enabled: true

# Needed to access the server, depending on your configuration
ingress:
  enabled: true
  className: ""
  hosts:
    - host: localhost
      paths:
        - path: /
          pathType: Prefix
      backend:
        service:
          name: opencti-server
          port: 
            number: 80
  tls: []
